# Generated by Django 5.2 on 2025-04-12 13:07

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cloud_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(help_text='Пользователь, которому принадлежит этот файл', on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cloud_app.folder', verbose_name='Родительская папка'),
        ),
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='Папка, в которой находится файл', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='cloud_app.folder', verbose_name='Папка'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('owner', 'parent', 'name')},
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('owner', 'folder', 'original_name'), name='unique_file_name_per_folder', violation_error_message='Файл с таким именем уже существует в указанной папке'),
        ),
    ]
